---

# Convenience variables for easy overwriting
bika_plone_version: "4.3.11"
bika_user: bika
bika_group: bika
bika_daemon_user: bika_daemon
bika_plone_initial_password: bika
bika_plone_instance_name: bikalims
bika_plone_site_id: bikalims
bika_plone_create_site: yes
bika_plone_target_path: "/home/{{ bika_user }}"
bika_plone_var_path: "/home/{{ bika_user }}/data"
bika_plone_backup_path: "{{ bika_plone_var_path }}"
bika_plone_additional_eggs:
  - bika.lims
  - Products.PloneHotfix20161129
  - Products.PloneHotfix20170117
bika_plone_additional_versions:
  - bika.lims=3.1.13
bika_plone_zcml_slugs: []
bika_plone_extension_profiles: []
bika_plone_client_extras:
bika_plone_client_count: 2
bika_plone_zserver_threads: 2
bika_plone_zeo_ip: 127.0.0.1
bika_plone_zeo_port: 8100
bika_plone_client_base_port: 8081
bika_plone_zodb_cache_size: 30000
bika_plone_extra_parts:
bika_plone_buildout_extra:
bika_plone_buildout_extra_parts:
bika_plone_sources:
bika_plone_environment_vars:
bika_plone_timezone:

# Supervisor Daemon HTTP
bika_supervisor_with_http: no
bika_supervisor_http_port: "127.0.0.1:9001"
bika_supervisor_http_user: "admin"
bika_supervisor_http_pass: "admin"

# DB Pack
bika_plone_pack_at:
  minute: 30
  hour: 1
  weekday: 7

bika_plone_keep_days: 3

# DB Backup
bika_plone_backup_at:
  minute: 30
  hour: 2
  weekday: "*"

bika_plone_keep_backups: 5
bika_plone_keep_blob_days: 21

# Bika Monitoring: Defined in an extras section to be independent if someone
# overwrites `bika_plone_additional_eggs`
bika_monitoring_eggs:
  - Products.ZNagios
bika_monitoring_zcml: []
bika_monitoring_versions:
  - Products.ZNagios=0.7.2
bika_zeo_monitor_port: 8999

# This configuration gets passed to the `plone_server` role, see
# `meta/main.yml`.
bika_plone_config:
  - plone_version: "{{ bika_plone_version }}"
    plone_group: "{{ bika_group }}"
    plone_buildout_user: "{{ bika_user }}"
    plone_daemon_user: "{{ bika_daemon_user }}"
    plone_initial_password: "{{ bika_plone_initial_password }}"
    plone_instance_name: "{{ bika_plone_instance_name }}"
    plone_site_id: "{{ bika_plone_site_id }}"
    plone_create_site: "{{ bika_plone_create_site }}"
    plone_target_path: "{{ bika_plone_target_path }}"
    plone_var_path: "{{ bika_plone_var_path }}"
    plone_backup_path: "{{ bika_plone_backup_path }}"
    plone_backup_at: "{{ bika_plone_backup_at }}"
    plone_keep_backups: "{{ bika_plone_keep_backups }}"
    plone_keep_blob_days: "{{ bika_plone_keep_blob_days }}"
    plone_pack_at: "{{ bika_plone_pack_at }}"
    plone_keep_days: "{{ bika_plone_keep_days }}"
    plone_additional_eggs: "{{ bika_plone_additional_eggs + bika_monitoring_eggs }}"
    plone_zcml_slugs: "{{ bika_plone_zcml_slugs + bika_monitoring_zcml }}"
    plone_additional_versions: "{{ bika_plone_additional_versions + bika_monitoring_versions }}"
    plone_extension_profiles: "{{ bika_plone_extension_profiles }}"
    plone_client_extras: "{{ bika_plone_client_extras }}"
    plone_client_count: "{{ bika_plone_client_count }}"
    plone_zserver_threads: "{{ bika_plone_zserver_threads }}"
    plone_zeo_port: "{{ bika_plone_zeo_port }}"
    plone_client_base_port: "{{ bika_plone_client_base_port }}"
    plone_zodb_cache_size: "{{ bika_plone_zodb_cache_size }}"
    plone_extra_parts: "{{ bika_plone_extra_parts }}"
    plone_buildout_extra: "{{ bika_plone_buildout_extra }}"
    plone_buildout_extra_parts: "{{ bika_plone_buildout_extra_parts }}"
    plone_sources: "{{ bika_plone_sources }}"
    plone_environment_vars: "{{ bika_plone_environment_vars }}"
    plone_timezone: "{{ bika_plone_timezone }}"
