---
sudo: required

env:
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Build the image from the specified dockerfile in the docker folder
  - 'sudo docker build --rm=true --file=docker/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible docker'

script:
  - container_id=$(mktemp)

  # Run container in detached state and mount the current directory to /bika
  - 'sudo docker run --detach --volume="${PWD}":/bika:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  # Install Ansible requirements
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install -r /bika/requirements.yml'

  # Ansible syntax check of `test.yml`
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /bika/test.yml --syntax-check'

  # Test Bika Role
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /bika/test.yml --skip-tags bika-security && exit 0'

  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'
