---

- name: Set Bika convenience variables
  set_fact:
    bika_config: "{{ bika_plone_config[0] }}"

- name: Insert Supervisor HTTP Server Block
  blockinfile:
    dest: /etc/supervisor/supervisord.conf
    block: |
      [inet_http_server]
      port = {{ bika_supervisor_http_port }}
      username = {{ bika_supervisor_http_user }}
      password = {{ bika_supervisor_http_pass }}
    state: present
  when: bika_supervisor_with_http
  notify: restart supervisor
  tags:
    - bika-supervisor

- name: Remove Supervisor HTTP Server Block
  blockinfile:
    dest: /etc/supervisor/supervisord.conf
    block: |
      [inet_http_server]
      port = {{ bika_supervisor_http_port }}
      username = {{ bika_supervisor_http_user }}
      password = {{ bika_supervisor_http_pass }}
    state: absent
  when: not bika_supervisor_with_http
  notify: restart supervisor
  tags:
    - bika-supervisor

- name: Insert ZEO Monitoring Block
  blockinfile:
    dest: "{{bika_plone_target_path}}/{{bika_plone_instance_name}}/parts/zeoserver/etc/zeo.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      monitor-address {{bika_plone_zeo_ip}}:{{bika_zeo_monitor_port}}
    state: present
    insertbefore: "</zeo>"
  notify: restart supervisor
  tags:
    - munin-znagios
    - bika-monitoring
